### ISSUE TITLE
cmake构建构建很多报错，但是用vs2017编译成功

### ISSUE THREAD

**Issue by royburns** [tashaxing/finarthur#1]
好久没弄c++了，我贴一下cmake的报错信息，这些不影响程序的编译跟运行吗？

CMake Warning (dev) at CMakeLists.txt:3 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    CMAKE_PROJECT_VERSION
    CMAKE_PROJECT_VERSION_MAJOR
    CMAKE_PROJECT_VERSION_MINOR
    CMAKE_PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning at thirdparty/glog-0.3.5/CMakeLists.txt:52 (find_package):
  By not providing "Findgflags.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "gflags", but
  CMake did not find one.

  Could not find a package configuration file provided by "gflags" with any
  of the following names:

    gflagsConfig.cmake
    gflags-config.cmake

  Add the installation prefix of "gflags" to CMAKE_PREFIX_PATH or set
  "gflags_DIR" to a directory containing one of the above files.  If "gflags"
  provides a separate development package or SDK, be sure it has been
  installed.

CURVE security is disabled
Detected select polling method
Detected ZMQ Version - 4.2.1
Checking whether SOCK_CLOEXEC is supported
Checking whether SO_KEEPALIVE is supported
Checking whether TCP_KEEPCNT is supported
Checking whether TCP_KEEPIDLE is supported
Checking whether TCP_KEEPINTVL is supported
Checking whether TCP_KEEPALIVE is supported
Checking whether TIPC is supported
Could NOT find AsciiDoc (missing: ASCIIDOC_EXECUTABLE) 
CMake Warning at thirdparty/curl-7.63.0/CMakeLists.txt:50 (message):
  the curl cmake build system is poorly maintained.  Be aware

curl version=[7.63.0]
CMake Warning at thirdparty/curl-7.63.0/CMake/Macros.cmake:86 (message):
  Found no *nroff program
Call Stack (most recent call first):
  thirdparty/curl-7.63.0/CMakeLists.txt:208 (curl_nroff_check)

Could NOT find Perl (missing: PERL_EXECUTABLE) 
Perl not found, testing disabled.
Could NOT find LibSSH2 (missing: LIBSSH2_INCLUDE_DIR LIBSSH2_LIBRARY) 
Enabled features: IPv6 AsynchDNS
Enabled protocols: DICT FILE FTP GOPHER HTTP IMAP LDAP POP3 RTSP SMTP TELNET TFTP
Configuring done
Generating done

**Comment by tashaxing** [comment]
不影响到，确保cmake和vc版本足够高，编译通过就行
