### ISSUE TITLE
修改了一处json配置文件的错误，但是还是运行报错，db提示打不开

### ISSUE THREAD

**Issue by royburns** [tashaxing/finarthur#2]
运行archer_trade.exe报错
json文件有个错误的地方，34行少一个‘,’，把这个问题修复后还是提示parse config file failed, 6

![image](https://user-images.githubusercontent.com/652375/54733670-c662ed00-4bd5-11e9-8cd8-8adb94f857d0.png)

**Comment by royburns** [comment]
其他的几个进程是可以启动的，找的刀config和db

**Comment by royburns** [comment]
感觉那个json文件还有错误的地方

**Comment by royburns** [comment]
好了，json文件就那一个地方错误，ok了

**Comment by tashaxing** [comment]
> 好了，json文件就那一个地方错误，ok了

谢谢提醒，已修复
使用的时候，你需要把ctp和xtp的账户信息配置进去
