### ISSUE TITLE
memset在windows下的表现跟linux下似乎不太一样

### ISSUE THREAD

**Issue by royburns** [tashaxing/finarthur#3]
finarthur\finarthur\archer_trade\src\front\client_front.cpp
line 1198
memset(&login_req, 0, sizeof(login_req));
说明：注释掉这行之后，login_req里面的字段就不是乱的了，怀疑memset在windows下的表现跟linux下似乎不太一样

![image](https://user-images.githubusercontent.com/652375/54738669-28c8e700-4bf0-11e9-9d41-29f902f9db8c.png)

**Comment by tashaxing** [comment]
这是个bug，对于自定义结构体，一般不用memset，谢谢提醒
已去掉
