### ISSUE TITLE
两个编译错误

### ISSUE THREAD

**Issue by physercoe** [tashaxing/finarthur#4]
编译环境： linux manjaro 18,  gcc 8.2
zutil-> string_helper.hpp->GbkToUtf8和Utf8ToGbk函数中的 *pout = '\0' 语句：gcc报错：无法从char 转换成 char *，注释掉后可以编译；
可视化vison模块：
npm install 时报错：Recharts模块找不到，将Recharts 改为rechars后通过。

**Comment by tashaxing** [comment]
- ubuntu下gcc能编译通过这句，其他发行版没试过
- 写的就是recharts，应该无需更改，看这个：[https://www.npmjs.com/package/recharts](https://www.npmjs.com/package/recharts)

**Comment by physercoe** [comment]
搜索关键字 Recharts，可以看到有三处from "Recharts"，在别的机器上是否可以找到不清楚，在我这提示找不到Recharts，需要改为recharts后才行：
finarthur/caster_vision/src/component/saber_analysis/brinson.js:
21 | import {BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend} from "**Recharts**";
22 | import log from "../../util/log";
finarthur/caster_vision/src/component/saber_analysis/invest_style.js:
15 | import {PieChart, Pie, Legend, Tooltip} from "**Recharts**";
finarthur/caster_vision/src/component/saber_analysis/netvalue_regression.js:
21 | import {Radar, RadarChart, PolarGrid, Legend, PolarAngleAxis, PolarRadiusAxis} from "**Recharts**";

**Comment by tashaxing** [comment]
> 搜索关键字 Recharts，可以看到有三处from "Recharts"，在别的机器上是否可以找到不清楚，在我这提示找不到Recharts，需要改为recharts后才行：
> finarthur/caster_vision/src/component/saber_analysis/brinson.js:
> 21 | import {BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend} from "**Recharts**";
> 22 | import log from "../../util/log";
> finarthur/caster_vision/src/component/saber_analysis/invest_style.js:
> 15 | import {PieChart, Pie, Legend, Tooltip} from "**Recharts**";
> finarthur/caster_vision/src/component/saber_analysis/netvalue_regression.js:
> 21 | import {Radar, RadarChart, PolarGrid, Legend, PolarAngleAxis, PolarRadiusAxis} from "**Recharts**";
可能不同机器不一样，已统一更改成 recharts
谢谢反馈
